VT_API_KEY: 'Enter VirusTotal API Key Here'
AB_API_KEY: 'Enter AbuseIPDB API Key Here'
URLSCAN_IO_KEY: 'Enter urlscan.io API Key Here'
HIBP_API_KEY: 'Enter HaveIBeenPwned API Key Here'
EMAILREP_API_KEY: 'Enter EmailRep.io API Key Here'

phishtank:
  appname: 'Enter Phishtank Application Name Here'
  api: 'Enter Phishtank API Key Here'
  download: False
